sudo: required
language: go
go:
  - 1.7
branches:
  only:
    - master
services:
  - docker
env:
  # HACK(bacongobbler): make travis tests work
  - DEIS_REGISTRY=travis-ci
install:
  - make docker-build
script:
  - make test
